### Create Student
POST localhost:8080/student
Content-Type: application/json

{
  "name":"Vali4",
  "surname":"Valiyev",
  "age":19,
  "gender": "FEMALE",
  "level": 1,
  "createdDate": "2024-10-23"
}
### pagination
GET localhost:8080/student/pagination

### filter
POST localhost:8080/student/filter
Content-Type: application/json

{
  "name":"Vali4"
}

### filter mark
POST localhost:8080/mark/filter
Content-Type: application/json

{
  "studentId": 1
}